
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(32)  NOT NULL,
    password_hash     VARCHAR(100) NOT NULL,
    public_key        VARCHAR(20000),
    key_fingerprint   VARCHAR(64),
    key_algorithm     VARCHAR(64),
    key_created_at    TIMESTAMP WITH TIME ZONE,
    key_uploaded_at   TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username)
);


CREATE TABLE conversations (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a_id        BIGINT NOT NULL REFERENCES users (id),
    user_b_id        BIGINT NOT NULL REFERENCES users (id),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    last_message_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_conversations_pair UNIQUE (user_a_id, user_b_id),
    CONSTRAINT ck_conversations_order CHECK (user_a_id < user_b_id)
);

CREATE INDEX ix_conversations_user_b ON conversations (user_b_id);

CREATE TABLE attachments (
    id               UUID PRIMARY KEY,
    conversation_id  BIGINT NOT NULL REFERENCES conversations (id),
    uploader_id      BIGINT NOT NULL REFERENCES users (id),
    size_bytes       BIGINT NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL REFERENCES conversations (id),
    sender_id        BIGINT NOT NULL REFERENCES users (id),
    ciphertext       VARCHAR(200000) NOT NULL,
    attachment_id    UUID REFERENCES attachments (id),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_messages_conversation ON messages (conversation_id, id);
